# Generated by Django 5.2.5 on 2026-04-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_servicio_familia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='familia',
            field=models.CharField(choices=[('Letreros', 'Letreros'), ('Creacion Diseño', 'Creación Diseño'), ('Adhesivo Vehicular', 'Adhesivo Vehicular'), ('Tecnologia Instalaciones', 'Tecnología Instalaciones'), ('Tecnologia Desarrollo', 'Tecnología Desarrollo'), ('Marketing Web', 'Marketing Web'), ('Marketing RRSS', 'Marketing RRSS'), ('Audiovisual', 'Audiovisual')], default='Letreros', max_length=50),
        ),
    ]
