# Generated by Django 5.2.5 on 2026-04-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_proceso_familia'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
