# Generated by Django 5.2.5 on 2026-02-25 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('taller', 'Taller'), ('diseno', 'Diseño')], max_length=20),
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acrilico', models.BooleanField(default=False)),
                ('sintra', models.BooleanField(default=False)),
                ('ojetillo', models.BooleanField(default=False)),
                ('ad_prom', models.BooleanField(default=False)),
                ('ad_vehicular', models.BooleanField(default=False)),
                ('empavonado', models.BooleanField(default=False)),
                ('microperf', models.BooleanField(default=False)),
                ('sellado', models.BooleanField(default=False)),
                ('tela_pvc', models.BooleanField(default=False)),
                ('impresion', models.BooleanField(default=False)),
                ('corte', models.BooleanField(default=False)),
                ('terminaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
