# Generated by Django 5.2.5 on 2026-02-25 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_condiciones_pago_proveedor_condiciones_pago'),
        ('usuarios', '0004_alter_perfil_tipo_usuario_proceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='clientes.cliente'),
            preserve_default=False,
        ),
    ]
