# Generated by Django 5.2.5 on 2026-04-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_proceso_familia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='familia',
            field=models.CharField(choices=[('Letreros', 'Letreros'), ('Creacion Diseño', 'Creación Diseño'), ('Adhesivo Vehicular', 'Adhesivo Vehicular'), ('Tecnologia Instalaciones', 'Tecnología Instalaciones'), ('Tecnologia Desarrollo', 'Tecnología Desarrollo'), ('Marketing Web', 'Marketing Web'), ('Marketing RRSS', 'Marketing RRSS'), ('Audiovisual', 'Audiovisual'), ('Adhesivos (stickers)', 'Adhesivos (stickers)')], default='Letreros', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='familia',
            field=models.CharField(choices=[('Letreros', 'Letreros'), ('Creacion Diseño', 'Creación Diseño'), ('Adhesivo Vehicular', 'Adhesivo Vehicular'), ('Tecnologia Instalaciones', 'Tecnología Instalaciones'), ('Tecnologia Desarrollo', 'Tecnología Desarrollo'), ('Marketing Web', 'Marketing Web'), ('Marketing RRSS', 'Marketing RRSS'), ('Audiovisual', 'Audiovisual'), ('Adhesivos (stickers)', 'Adhesivos (stickers)')], max_length=50),
        ),
    ]
