# Generated by Django 5.2.5 on 2026-02-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_proceso_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('ADH', 'Adhesivos'), ('TEL', 'Telas'), ('RIG', 'Materiales Rígidos'), ('TIN', 'Tintas Plotter'), ('LIM', 'Limpieza'), ('REP', 'Repuestos Taller')], max_length=3)),
                ('variedad', models.CharField(blank=True, help_text='Ej: Mate, Brillante, 3mm', max_length=50)),
                ('nivel_actual', models.IntegerField(default=100)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
