# Generated by Django 5.2.5 on 2026-02-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_materialstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstock',
            name='categoria',
            field=models.CharField(choices=[('ADH', 'Adhesivos'), ('TEL', 'Telas'), ('RIG', 'Materiales Rígidos'), ('TIN', 'Tintas Plotter Xenons DX5'), ('LIM', 'Limpieza'), ('REP', 'Repuestos Taller')], max_length=3),
        ),
    ]
