# Generated by Django 5.2.5 on 2026-04-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_proceso_familia_alter_servicio_familia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('taller', 'Taller'), ('diseno', 'Diseño'), ('administracion', 'Administracion'), ('vendedor', 'Vendedor')], max_length=20),
        ),
    ]
