# Generated by Django 5.2.5 on 2026-02-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_materialstock_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('taller', 'Taller'), ('diseno', 'Diseño'), ('administracion', 'Administracion')], max_length=20),
        ),
    ]
