# Generated by Django 5.2.5 on 2026-04-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_perfil_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='codigo_vendedor',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
