# Generated by Django 5.2.5 on 2026-02-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='codigo',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
