# Generated by Django 5.2.5 on 2026-04-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_cotizacionarticulo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='total_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor_abonado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
