# Generated by Django 5.2.5 on 2026-02-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_articulo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='familia',
            field=models.CharField(choices=[('Adhesivos', 'Adhesivos'), ('Merchandising', 'Merchandising'), ('Tecnologia', 'Tecnología')], default='Tecnologia', max_length=50),
        ),
    ]
