# Generated by Django 5.2.5 on 2026-02-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_articulo_familia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=10, unique=True)),
                ('familia', models.CharField(choices=[('Letreros', 'Letreros'), ('Creacion Diseño', 'Creación Diseño'), ('Adhesivo Vehicular', 'Adhesivo Vehicular'), ('Tecnologia Instalaciones', 'Tecnología Instalaciones'), ('Tecnologia Desarrollo', 'Tecnología Desarrollo'), ('Marketing Web', 'Marketing Web'), ('Marketing RRSS', 'Marketing RRSS')], max_length=50)),
                ('descripcion', models.TextField()),
                ('costo_m2', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
