# Generated by Django 5.2.5 on 2026-04-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_compra_total_compra_alter_compra_valor_abonado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_facturado',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='factura',
            name='valor_abonado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
