# Generated by Django 5.2.5 on 2026-02-27 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_condiciones_pago_proveedor_condiciones_pago'),
        ('usuarios', '0012_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionArticulo',
            fields=[
                ('n_presupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCotizacionArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.articulo')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='usuarios.cotizacionarticulo')),
            ],
        ),
    ]
