# Generated by Django 5.2.5 on 2026-02-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_cotizacionarticulo_cotizacionservicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecotizacionarticulo',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
