# Generated by Django 5.2.5 on 2026-02-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_detallecotizacionarticulo_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
