# Generated by Django 5.2.5 on 2026-02-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_articulo_margen_ganancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='aprobacion_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proceso',
            name='correccion_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proceso',
            name='correccion_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proceso',
            name='correccion_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proceso',
            name='enviado_correccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('diseno', 'En Diseño (Pauta/Correcciones)'), ('taller', 'En Taller (Producción)'), ('finalizado', 'Finalizado (Pendiente Admin)'), ('cerrado', 'Cerrado/Entregado')], default='diseno', max_length=20),
        ),
        migrations.AddField(
            model_name='proceso',
            name='pauta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proceso',
            name='responsable_proyecto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='reunion',
            field=models.BooleanField(default=False),
        ),
    ]
