# Generated by Django 5.2.5 on 2026-03-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_accionhistorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='pasa_por_diseno',
            field=models.BooleanField(default=True, verbose_name='¿Requiere Diseño?'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='pasa_por_taller',
            field=models.BooleanField(default=True, verbose_name='¿Requiere Taller?'),
        ),
    ]
