# Generated by Django 5.2.5 on 2026-03-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_proceso_pasa_por_diseno_proceso_pasa_por_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='aprobacion_taller',
            field=models.BooleanField(default=False),
        ),
    ]
