# Generated by Django 5.2.5 on 2026-02-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='condiciones_pago',
            field=models.CharField(choices=[('60', '60 días'), ('30', '30 días'), ('15', '15 días'), ('0', 'Contado')], default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='condiciones_pago',
            field=models.CharField(choices=[('60', '60 días'), ('30', '30 días'), ('15', '15 días'), ('0', 'Contado')], default='0', max_length=2),
        ),
    ]
